[package]
name = "QuarkEngine"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.9.2" }

[build-dependencies]
dirs = "5"   # or latest version
toml = "0.7" # or latest version compatible